//---------------------------------------------------------//
// Ingredients List for Each Recipes in Alphabetical Order //


//---------------------------------------------------------//
export const seedIngredientMeasUnit = [
  // Airy Thick Crust Pizza
  {recipe_id: 'airy-thick-crust-pizza', component: 'Dough:', amount: '1 1/3', measUnit_id: 'cup(s)', ingredient_id: 'Water', min_amount: '1 1/3'},
  {recipe_id: 'airy-thick-crust-pizza', component: 'Dough:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Granulated Sugar', min_amount: '1'},
  {recipe_id: 'airy-thick-crust-pizza', component: 'Dough:', amount: '2 1/4', measUnit_id: 'tsp(s)', ingredient_id: 'Yeast', min_amount: '2 1/4'},
  {recipe_id: 'airy-thick-crust-pizza', component: 'Dough:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Olive Oil', min_amount: '2'},
  {recipe_id: 'airy-thick-crust-pizza', component: 'Dough:', amount: '2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '2'},
  {recipe_id: 'airy-thick-crust-pizza', component: 'Dough:', amount: '3 1/2', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '3 1/2'},
  {recipe_id: 'airy-thick-crust-pizza', component: 'Sauce:', amount: '1 1/2', measUnit_id: 'cup(s)', ingredient_id: 'Tomato Sauce', min_amount: '1 1/2'},
  {recipe_id: 'airy-thick-crust-pizza', component: 'Sauce:', amount: '2', measUnit_id: 'tsp(s)', ingredient_id: 'Cayenne Pepper', min_amount: '2'},
  {recipe_id: 'airy-thick-crust-pizza', component: 'Toppings:', amount: '2', measUnit_id: 'cup(s)', ingredient_id: 'Mozzarella Cheese', min_amount: '2'},
  {recipe_id: 'airy-thick-crust-pizza', component: 'Toppings:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Pepperoni', min_amount: '1/2'},
  // Apple Frangipane Tart
  {recipe_id: 'apple-frangipane-tart', component: 'Dough:', amount: '1', measUnit_id: ' ', ingredient_id: 'Premade 9 inch Pie Crust', min_amount: '1'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '4', measUnit_id: 'tbsp(s)', ingredient_id: 'Unsalted Butter', min_amount: '4'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Granulated Sugar', min_amount: '1/4'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Almond Flour', min_amount: '1/2'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '1/4', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/4'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '1', measUnit_id: 'tbsp(s)', ingredient_id: 'Flour', min_amount: '1'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '1', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '1'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Vanilla Extract', min_amount: '1'},
  {recipe_id: 'apple-frangipane-tart', component: 'Toppings:', amount: '2', measUnit_id: ' ', ingredient_id: 'Apple(s)', min_amount: '2'},
  //Black Sesame Paste
  {recipe_id: 'black-sesame-paste', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Black Sesame Seeds', min_amount: '1/2'},
  {recipe_id: 'black-sesame-paste', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Water', min_amount: '2'},
  {recipe_id: 'black-sesame-paste', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Honey / Maple Syrup', min_amount: '1/4'},
  //Black Sesame Swirl Buns
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '3/4', measUnit_id: 'cup(s)', ingredient_id: 'Whole Milk', min_amount: '3/4'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '2 1/4', measUnit_id: 'tsp(s)', ingredient_id: 'Yeast', min_amount: '2 1/4'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Granulated Sugar', min_amount: '1/4'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '1', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '1'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '1', measUnit_id: ' ', ingredient_id: 'Egg Yolk(s)', min_amount: '1'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Unsalted Butter', min_amount: '1/4'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '2 3/4', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '2 3/4'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Black Sesame Paste:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Black Sesame Seeds', min_amount: '1/2'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Black Sesame Paste:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Honey / Maple Syrup', min_amount: '1/4'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Filling:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Unsalted Butter', min_amount: '2'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Filling:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Black Sesame Paste', min_amount: '1/2'},
  //Blueberry Rolls
  {recipe_id: 'blueberry-rolls', component: 'Dough:', amount: '3/4', measUnit_id: 'cup(s)', ingredient_id: 'Whole Milk', min_amount: '3/4'},
  {recipe_id: 'blueberry-rolls', component: 'Dough:', amount: '2 1/4', measUnit_id: 'tsp(s)', ingredient_id: 'Yeast', min_amount: '2 1/4'},
  {recipe_id: 'blueberry-rolls', component: 'Dough:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Granulated Sugar', min_amount: '1/4'},
  {recipe_id: 'blueberry-rolls', component: 'Dough:', amount: '1', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '1'},
  {recipe_id: 'blueberry-rolls', component: 'Dough:', amount: '1', measUnit_id: ' ', ingredient_id: 'Egg Yolk(s)', min_amount: '1'},
  {recipe_id: 'blueberry-rolls', component: 'Dough:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Unsalted Butter', min_amount: '1/4'},
  {recipe_id: 'blueberry-rolls', component: 'Dough:', amount: '2 3/4', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '2 3/4'},
  {recipe_id: 'blueberry-rolls', component: 'Dough:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'blueberry-rolls', component: 'Filling:', amount: '3', measUnit_id: 'tbsp(s)', ingredient_id: 'Unsalted Butter', min_amount: '3'},
  {recipe_id: 'blueberry-rolls', component: 'Filling:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Granulated Sugar', min_amount: '1/2'},
  {recipe_id: 'blueberry-rolls', component: 'Filling:', amount: '2', measUnit_id: ' ', ingredient_id: 'Lemon(s)', min_amount: '2'},
  {recipe_id: 'blueberry-rolls', component: 'Filling:', amount: '2', measUnit_id: 'cup(s)', ingredient_id: 'Blueberries', min_amount: '2'},
  //Chocolate Chip Cookies
  {recipe_id: 'chocolate-chip-cookies', amount: '3/4', measUnit_id: 'cup(s)', ingredient_id: 'Unsalted Butter', min_amount: '3/8'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Margarine', min_amount: '1/8'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Granulated Sugar', min_amount: '1/4'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1', measUnit_id: 'cup(s)', ingredient_id: 'Brown Sugar', min_amount: '1/2'},
  {recipe_id: 'chocolate-chip-cookies', amount: '2', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '1'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Vanilla Extract', min_amount: '1/2'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1/8', measUnit_id: 'tsp(s)', ingredient_id: 'Ground Cinnamon', min_amount: '1/16'},
  {recipe_id: 'chocolate-chip-cookies', amount: '2 1/4', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '1 1/8'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Baking Soda', min_amount: '1/2'},
  {recipe_id: 'chocolate-chip-cookies', amount: '2', measUnit_id: 'cup(s)', ingredient_id: 'Semisweet Chocolate Chips', min_amount: '1'},
  //Chocolate Raspberry Mousse Cake
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Water', min_amount: '1/4'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '4', measUnit_id: 'tsp(s)', ingredient_id: 'Canola Oil', min_amount: '4'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '2', measUnit_id: 'tsp(s)', ingredient_id: 'White Vinegar', min_amount: '2'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '1/3', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '1/3'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '3', measUnit_id: 'tbsp(s)', ingredient_id: 'Granulated Sugar', min_amount: '3'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '1 1/2', measUnit_id: 'tbsp(s)', ingredient_id: 'Cocoa Powder', min_amount: '1 1/2'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '1/8', measUnit_id: 'tsp(s)', ingredient_id: 'Baking Soda', min_amount: '1/8'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Gelatin Powder', min_amount: '1'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1', measUnit_id: 'tbsp(s)', ingredient_id: 'Water', min_amount: '1'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '2', measUnit_id: 'cup(s)', ingredient_id: 'Raspberries', min_amount: '2'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Lemon Juice', min_amount: '1'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Vanilla Extract', min_amount: '1'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1', measUnit_id: 'tbsp(s)', ingredient_id: 'Granulated Sugar', min_amount: '1'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1/8', measUnit_id: 'cup(s)', ingredient_id: 'Water', min_amount: '1/8'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Heavy Cream', min_amount: '1/4'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Mousse:', amount: '140', measUnit_id: 'g', ingredient_id: 'Dark Chocolate, chopped', min_amount: '140'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Mousse:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Gelatin Powder', min_amount: '1'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Mousse:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Water', min_amount: '2'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Mousse:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Granulated Sugar', min_amount: '1/2'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Mousse:', amount: '1 1/3', measUnit_id: 'cup(s)', ingredient_id: 'Heavy Cream', min_amount: '1 1/3'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Ganache Glaze:', amount: '85', measUnit_id: 'g', ingredient_id: 'Dark Chocolate, chopped', min_amount: '85'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Ganache Glaze:', amount: '1/3', measUnit_id: 'cup(s)', ingredient_id: 'Heavy Cream', min_amount: '1/3'},
  //Cici's Addictive Guacamole
  {recipe_id: 'cicis-addictive-guacamole', amount: '4', measUnit_id: ' ', ingredient_id: 'Avocado(s)', min_amount:'2'},
  {recipe_id: 'cicis-addictive-guacamole', amount: '1/2', measUnit_id: ' ', ingredient_id: 'Lime(s)', min_amount:'1/4'},
  {recipe_id: 'cicis-addictive-guacamole', amount: '1/2', measUnit_id: ' ', ingredient_id: 'Red Onion, diced', min_amount:'1/4'},
  {recipe_id: 'cicis-addictive-guacamole', amount: '1/2', measUnit_id: ' ', ingredient_id: 'Tomato(s)', min_amount:'1/4'},
  {recipe_id: 'cicis-addictive-guacamole', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Garlic Powder', min_amount:'1/2'},
  {recipe_id: 'cicis-addictive-guacamole', amount: '2', measUnit_id: 'tsp(s)', ingredient_id: 'Celery Salt', min_amount:'1'},
  {recipe_id: 'cicis-addictive-guacamole', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Black Pepper', min_amount:'1/4'},
  {recipe_id: 'cicis-addictive-guacamole', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount:'1/4'},
  //Dijon Mustard Vinagrette
  {recipe_id: 'dijon-mustard-vinaigrette', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Olive Oil', min_amount: '1/2' },
  {recipe_id: 'dijon-mustard-vinaigrette', amount: '3', measUnit_id: 'tbsp(s)', ingredient_id: 'Red Wine Vinegar / Apple Cider Vinegar', min_amount: '3' },
  {recipe_id: 'dijon-mustard-vinaigrette', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Honey / Maple Syrup', min_amount: '2' },
  {recipe_id: 'dijon-mustard-vinaigrette', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Dijon Mustard, whole grain', min_amount: '2' },
  {recipe_id: 'dijon-mustard-vinaigrette', amount: '1 1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Garlic Powder', min_amount: '1 1/2' },
  {recipe_id: 'dijon-mustard-vinaigrette', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2' },
  {recipe_id: 'dijon-mustard-vinaigrette', amount: '1 1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Black Pepper', min_amount: '1 1/2' },
  // Fluffy Blueberry Muffins
  {recipe_id: 'fluffy-blueberry-muffins', amount: '1/3', measUnit_id: 'cup(s)', ingredient_id: 'Unsalted Butter', min_amount: '1/3'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Vegetable Oil', min_amount: '2'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '1', measUnit_id: 'cup(s)', ingredient_id: 'Brown Sugar', min_amount: '1'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '2', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '2'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Vanilla Extract', min_amount: '1'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Milk', min_amount: '1/2'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '2', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '2'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '2', measUnit_id: 'tsp(s)', ingredient_id: 'Baking Powder', min_amount: '2'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '2', measUnit_id: 'cup(s)', ingredient_id: 'Blueberries', min_amount: '2'},
  //Grammy Vint's Good Bean Salad
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: '19 oz can', ingredient_id: 'Chickpeas', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: '19 oz can', ingredient_id: 'Kidney Beans', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: '15 oz can', ingredient_id: 'Black Beans', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: '12 oz can', ingredient_id: 'Corn Kernels', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Red Onion, diced', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: ' ', ingredient_id: 'Sweet Red Pepper, diced', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Red Wine Vinegar / Apple Cider Vinegar', min_amount: '1/2'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Basil', min_amount: '2'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1/3', measUnit_id: 'cup(s)', ingredient_id: 'Olive Oil', min_amount: '1/3'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: 'tbsp(s)', ingredient_id: 'Dijon Mustard', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: 'clove(s) of', ingredient_id: 'Garlic, minced', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Hot Sauce', min_amount: '1/2'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Black Pepper', min_amount: '1/2'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Fresh Parsley', min_amount: '1/2'},
  //Grammy Vint's Rhubarb Cream Crisp
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Filling:', amount: '3', measUnit_id: 'cup(s)', ingredient_id: 'Rhubarb, chopped', min_amount: '3'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Filling:', amount: '2', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '2'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Filling:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Unsalted Butter', min_amount: '2'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Filling:', amount: '1', measUnit_id: 'cup(s)', ingredient_id: 'Granulated Sugar', min_amount: '1'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Filling:', amount: '3', measUnit_id: 'tbsp(s)', ingredient_id: 'Flour', min_amount: '3'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Crumble Topping:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '1/2'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Crumble Topping:', amount: '3/4', measUnit_id: 'cup(s)', ingredient_id: 'Quick Oats', min_amount: '3/4'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Crumble Topping:', amount: '3/4', measUnit_id: 'cup(s)', ingredient_id: 'Brown Sugar', min_amount: '3/4'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Crumble Topping:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Baking Powder', min_amount: '1'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Crumble Topping:', amount: '1/3', measUnit_id: 'cup(s)', ingredient_id: 'Unsalted Butter', min_amount: '1/3'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Crumble Topping:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Walnuts (optional)', min_amount: '1/4'},
  //Lemongrass Beef
  {recipe_id: 'lemongrass-beef', amount: '1', measUnit_id:'lb(s)', ingredient_id: 'Beef', min_amount: '1'},
  {recipe_id: 'lemongrass-beef', amount: '3', measUnit_id:'stalk(s) of', ingredient_id: 'Lemongrass', min_amount: '3'},
  {recipe_id: 'lemongrass-beef', amount: '1', measUnit_id:'inch piece of', ingredient_id: 'Fresh Ginger', min_amount: '1'},
  {recipe_id: 'lemongrass-beef', amount: '4', measUnit_id:'clove(s) of', ingredient_id: 'Garlic, minced', min_amount: '4'},
  {recipe_id: 'lemongrass-beef', amount: '1', measUnit_id:'tbsp(s)', ingredient_id: 'Oyster Sauce', min_amount: '1'},
  {recipe_id: 'lemongrass-beef', amount: '1', measUnit_id:'tbsp(s)', ingredient_id: 'Fish Sauce', min_amount: '1'},
  {recipe_id: 'lemongrass-beef', amount: '1', measUnit_id:'tbsp(s)', ingredient_id: 'Brown Sugar', min_amount: '1'},
  {recipe_id: 'lemongrass-beef', amount: '1/2', measUnit_id:'tbsp(s)', ingredient_id: 'Vegetable Oil', min_amount: '1/2'},
  //Mango Salsa
  {recipe_id: 'mango-salsa', amount: '1', measUnit_id: ' ', ingredient_id: 'Red Mango(s)', min_amount: '1'},
  {recipe_id: 'mango-salsa', amount: '1', measUnit_id: ' ', ingredient_id: 'Avocado(s)', min_amount: '1'},
  {recipe_id: 'mango-salsa', amount: '1', measUnit_id: 'tbsp(s)', ingredient_id: 'Lime Juice', min_amount: '1'},
  {recipe_id: 'mango-salsa', amount: '1/2', measUnit_id: ' ', ingredient_id: 'Red Onion, diced', min_amount: '1/2'},
  {recipe_id: 'mango-salsa', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Fresh Cilantro/Coriander', min_amount: '1/4'},
  {recipe_id: 'mango-salsa', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'mango-salsa', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Black Pepper', min_amount: '1/2'},
  {recipe_id: 'mango-salsa', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Hot Sauce', min_amount: '1'},
  //Merry Minced Meat Pies
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '100', measUnit_id: 'g', ingredient_id: 'Orange Marmelade', min_amount: '100'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '100', measUnit_id: 'g', ingredient_id: 'Raisins', min_amount: '100'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '200', measUnit_id: 'g', ingredient_id: 'Golden Raisins', min_amount: '200'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '100', measUnit_id: 'g', ingredient_id: 'Cranberries', min_amount: '100'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '50', measUnit_id: 'ml', ingredient_id: 'Orange Juice', min_amount: '50'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '110', measUnit_id: 'g', ingredient_id: 'Brown Sugar', min_amount: '110'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '1', measUnit_id: ' ', ingredient_id: 'Apple(s)', min_amount: '1'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '1/2', measUnit_id: ' ', ingredient_id: 'Lemon(s)', min_amount: '1/2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '1 1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Ground Cinnamon', min_amount: '1 1/2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Ginger Powder', min_amount: '1/2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Ground Cloves', min_amount: '1/2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Black Pepper', min_amount: '1/2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '125', measUnit_id: 'g', ingredient_id: 'Unsalted Butter', min_amount: '125'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '3', measUnit_id: 'tbsp(s)', ingredient_id: 'Brandy / Rum / Whiskey', min_amount: '3'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '250', measUnit_id: 'g', ingredient_id: 'Flour', min_amount: '250'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Almond Flour', min_amount: '2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '50', measUnit_id: 'g', ingredient_id: 'Granulated Sugar', min_amount: '50'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '150', measUnit_id: 'g', ingredient_id: 'Unsalted Butter', min_amount: '150'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '1', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '125'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '4', measUnit_id: 'tbsp(s)', ingredient_id: 'Ice Cold Water', min_amount: '4'},
  // Onion Pancakes
  {recipe_id: 'onion-pancakes', component: 'Dough:', amount: '1 3/4', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '1 3/4'},
  {recipe_id: 'onion-pancakes', component: 'Dough:', amount: '3', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '3'},
  {recipe_id: 'onion-pancakes', component: 'Dough:', amount: '1', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '1'},
  {recipe_id: 'onion-pancakes', component: 'Dough:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Hot Water', min_amount: '1/2'},
  {recipe_id: 'onion-pancakes', component: 'Dough:', amount: '3', measUnit_id: ' ', ingredient_id: "Tips of Green Onions", min_amount: '3'},
  {recipe_id: 'onion-pancakes', component: 'Spread:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Salted Butter', min_amount: '1/4'},
  {recipe_id: 'onion-pancakes', component: 'Spread:', amount: '3', measUnit_id: ' ', ingredient_id: 'Whites of Green Onions', min_amount: '3'},
  //Thai Chicken Peanut Noodles
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Vegetable Oil', min_amount: '2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '4', measUnit_id: 'clove(s) of', ingredient_id: 'Garlic, minced', min_amount: '4'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Ginger Powder', min_amount: '1'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '1', measUnit_id: ' ', ingredient_id: 'Lime(s)', min_amount: '1'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Coriander', min_amount: '1/4'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '4', measUnit_id: ' ', ingredient_id: 'Chicken Thighs, boneless', min_amount: '4'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Peanut Sauce:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Water', min_amount: '1/4'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Peanut Sauce:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Granulated Sugar', min_amount: '2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Peanut Sauce:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Peanut Butter', min_amount: '1/4'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Peanut Sauce:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Soy Sauce', min_amount: '2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Peanut Sauce:', amount: '1', measUnit_id: 'clove(s) of', ingredient_id: 'Garlic, minced', min_amount: '1'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Peanut Sauce:', amount: '2', measUnit_id: 'tsp(s)', ingredient_id: 'Sriracha', min_amount: '2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Noodles:', amount: '12', measUnit_id: 'oz(s)', ingredient_id: 'Vermicelli Noodles', min_amount: '12'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Stir Fry:', amount: '2', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Stir Fry:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Stir Fry:', amount: '1', measUnit_id: 'tbsp(s)', ingredient_id: 'Vegetable Oil', min_amount: '1'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Stir Fry:', amount: '1', measUnit_id: ' ', ingredient_id: 'Onion(s)', min_amount: '1'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Stir Fry:', amount: '1', measUnit_id: ' ', ingredient_id: 'Carrot(s)', min_amount: '1'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Stir Fry:', amount: '1', measUnit_id: ' ', ingredient_id: 'Zucchini', min_amount: '1'},
  // Water Spinach with Fermented Bean Curd Sauce
  {recipe_id: 'water-spinach-with-fermented-tofu-sauce', amount: '2', measUnit_id: 'bunch(es) of', ingredient_id: 'Water Spinach | Ong Choy | Kōng Xīn Cài 空心菜', min_amount: '1'},
  {recipe_id: 'water-spinach-with-fermented-tofu-sauce', amount: '6', measUnit_id: 'cube(s) of', ingredient_id: 'Fermented Bean Curd', min_amount: '3'},
  {recipe_id: 'water-spinach-with-fermented-tofu-sauce', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Shào Xīng Cooking Wine', min_amount: '1'},
  {recipe_id: 'water-spinach-with-fermented-tofu-sauce', amount: '2', measUnit_id: 'tsp(s)', ingredient_id: 'White Pepper', min_amount: '1'},
  {recipe_id: 'water-spinach-with-fermented-tofu-sauce', amount: '4', measUnit_id: 'clove(s) of', ingredient_id: 'Garlic, minced', min_amount: '3'},
  {recipe_id: 'water-spinach-with-fermented-tofu-sauce', amount: '1', measUnit_id: 'inch piece of', ingredient_id: 'Fresh Ginger', min_amount: '1/2'},
];