import { Noto_Sans_Telugu } from 'next/font/google';
import { db } from './index';
import { recipes, ingredients, measurementUnits, recipe_ingredient_measUnit} from './schema';
import { basename } from 'path';
import { title } from 'process';
import { max } from 'drizzle-orm';
import { create } from 'domain';

//------------------------------------------------//
// Seed Ingredients in Alphabetical Order         //
//------------------------------------------------//
const seedIngredients = [
    {ingr: 'Almond Flour'}, {ingr: 'Apple(s)'},
    {ingr: 'Baking Powder'}, { ingr: 'Baking Soda'}, {ingr: 'Basil'}, {ingr: 'Black Beans'}, {ingr: 'Black Pepper'}, {ingr: 'Black Sesame Paste'}, {ingr: 'Black Sesame Seeds'}, { ingr: 'Blueberries'}, {ingr: 'Brandy / Rum / Whiskey'}, { ingr: 'Brown Sugar'}, 
    {ingr: 'Canola Oil'}, {ingr: "Carrot(s)"}, {ingr: 'Chicken Thighs, boneless'}, {ingr: 'Chickpeas'}, {ingr: 'Cinnamon'}, {ingr: 'Cocoa Powder'}, {ingr: 'Coriander'}, {ingr: 'Coriander Powder'}, {ingr: 'Cornstarch'}, {ingr: 'Corn Kernels'}, {ingr: 'Cranberries'},
    {ingr: 'Dark Chocolate, chopped'}, {ingr: 'Dijon Mustard'},
    {ingr: 'Egg(s)'}, {ingr: 'Egg White(s)'}, {ingr: 'Egg Yolk(s)'},
    {ingr: 'Flour' }, {ingr: 'Fresh Fruit'}, {ingr: 'Fresh Parsley'},
    {ingr: 'Garlic, minced'}, {ingr: 'Gelatin Powder'}, {ingr: 'Ginger Powder'}, {ingr: 'Golden Raisins'}, {ingr: 'Granulated Sugar'}, { ingr: 'Tips of Green Onions' }, { ingr: 'Ground Cinnamon'}, {ingr: 'Ground Cloves'},
    {ingr: 'Heavy Cream'}, {ingr: 'Honey / Maple Syrup'}, { ingr: 'Hot Water' }, {ingr: 'Hot Sauce'},
    {ingr: 'Ice Cold Water'},
    {ingr: 'Kidney Beans'},
    {ingr: 'Lemon(s)'},{ingr: 'Lemon Juice'}, {ingr: 'Lime'},
    {ingr: 'Margarine' }, { ingr: 'Milk' }, 
    {ingr: 'Olive Oil'}, {ingr: 'Onion(s)'}, {ingr: 'Orange Juice'}, {ingr: 'Orange Marmelade'},
    {ingr: 'Peaches'}, {ingr: 'Peanut Butter'}, {ingr: 'Premade 9 inch Pie Crust'},
    {ingr: 'Quick Oats'},
    {ingr: 'Raisins'}, {ingr: 'Raspberries'}, {ingr: 'Red Onion, diced'}, {ingr: 'Red Wine Vinegar / Apple Cider Vinegar'}, {ingr: 'Rhubarb, chopped'},
    {ingr: 'Salt' }, { ingr: 'Salted Butter' }, {ingr: 'Semisweet Chocolate Chips'}, {ingr: 'Sriracha'}, {ingr: 'Soy Sauce'}, {ingr: 'Sweet Red Pepper, diced'}, 
    {ingr: 'Unsalted Butter' }, 
    {ingr: 'Vanilla Extract' }, { ingr: 'Vegetable Oil'}, {ingr: 'Vermicelli Noodles'},
    {ingr: 'Walnuts (optional)'}, {ingr: 'Water'}, {ingr: 'White Vinegar'}, {ingr: 'Whites of Green Onions'}, {ingr: 'White Wine Vinegar / Apple Cider Vinegar / Lemon Juice'}, {ingr: 'Whole Milk'},
    {ingr: 'Yeast'}, 
    {ingr: 'Zucchini'},
];

//------------------------------------------------//
// Insert measurementsUnits                       //
//------------------------------------------------//
const seedMeasurementUnits =[
    {meas_unit: ' '}, {meas_unit: '12 oz can'}, {meas_unit: '15 oz can'}, {meas_unit: '19 oz can'}, 
    {meas_unit: 'clove(s) of'}, { meas_unit: 'cup(s)'}, 
    {meas_unit: 'g'}, 
    {meas_unit: 'ml'},
    {meas_unit: 'oz(s)'}, 
    {meas_unit: 'sprigs of'},
    { meas_unit: 'tbsp(s)'}, {meas_unit: 'tsp(s)'},
];

//------------------------------------------------//
// Seed Recipes in Alphabetical Order             //
//------------------------------------------------//
const seedRecipes = [
  {
    title: "Apple Frangipane Tart",
    slug: "apple-frangipane-tart",
    tags: JSON.stringify(["Desserts"]),
    image: "/images/apple-frangipane-tart.png",
    rating: 5,
    views: 3,
    bookmarked: false,
    featured: true,
    cookTime: "1h",
    baseServings: 12,
    minServings: 12,
    servingIncrement: 12,
    directions: JSON.stringify([
      "title: Filling:",
      "Cream the butter and sugar together until fluffy.",
      "Add in all other ingredients for the filling until well-combined.",
      "title: Assemble:",
      "Preheat the oven to 375\u00B0F.",
      "Pour the filling mixture into the premade pie crust and use a spatula to spread the filling evenly.",
      "Slice the apples thinly and layer them in any pattern you wish on top of the filling.",
      "Bake the tart for 30-35 mins."
    ]),
    createdAt: new Date(2023, 5, 1),
  },
  {
    title: "Black Sesame Paste",
    slug: "black-sesame-paste",
    tags: JSON.stringify(["Easecipes"]),
    image: "/images/black-sesame-paste.png",
    rating: 5,
    views: 5,
    bookmarked: false,
    featured: true,
    cookTime: "10 min",
    baseServings: 1,
    minServings: 1,
    servingIncrement: 1,
    directions: JSON.stringify([
      "Toast the black sesame seeds in a dry pan over medium heat until fragrant, around 3-5 mins. Be careful not to burn them.",
      "Add the toasted black sesame seeds and water to a blender or food processor and blend until smooth. You may need to stop and scrape down the sides of the blender a few times to get everything blended well.",
      "Add honey or maple syrup to taste if you want a sweeter paste. Blend again until well-combined.",
      "Use the paste immediately, or store in an airtight container in the fridge for up to 2 weeks."
    ]),
    createdAt: new Date(2025, 12, 28),
  },
  {
    title: "Black Sesame Swirl Buns",
    slug: "black-sesame-swirl-buns",
    tags: JSON.stringify(["Breakfast", "Desserts"]),
    image: "/images/black-sesame-swirl-buns.jpg",
    rating: 5,
    views: 6,
    bookmarked: false,
    featured: false,
    cookTime: "5h",
    baseServings: 12,
    minServings: 12,
    servingIncrement: 12,
    directions: JSON.stringify([
      "title: Dough:",
      "Bloom the yeast in the warmed milk and set aside.",
      "In a mixer, cream the butter with the sugar.",
      "Add the eggs and the bloomed yeast mixture. Mix until well-combined.",
      "Add the flour and salt. Mix until well-combined.",
      "Mix for 10 minutes.",
      "Cover and set the dough aside in a well-oiled bowl until it has doubled in size. ",
      "title: Black Sesame Paste:",
      "While the dough is resting, make your black sesame paste by blending toasted black sesame seeds with 2 tbsps of water. ",
      "Once blended, add honey. Add more to taste if required.",
      "title: Assemble:",
      "Once the dough has doubled in size, roll out the dough into a 9x11 inch rectangle.",
      "Spread room-temperature butter onto the dough, leaving a 1/4 inch lip on the far side. Then spread the black sesame paste on top of the buttered surface.",
      "Roll the dough into a log shape, starting from the close side. Cut your rolled log of dough into 12 portions. <br><i><b>Tip:</b> Use unflavoured floss to cut the dough so that it stays round.</i>",
      "Grease a 9x11 inch pan and place the rolls in the pan. Cover and place in a warm spot to let rise for 30-45 mins.",
      "Preheat the oven to 350\u00B0F. Bake the rolls for 20-25 mins.",
    ]),
    createdAt: new Date(2025, 12, 28),
  },
  {
    title: "Chocolate Chip Cookies",
    slug: "chocolate-chip-cookies",
    tags: JSON.stringify(["Desserts", "Easecipes"]),
    image: "/images/chocolate-chip-cookies.png",
    rating: 4,
    views: 12,
    bookmarked: false,
    featured: false,
    cookTime: "30 min",
    baseServings: 24,
    minServings: 12,
    servingIncrement: 12,
    directions: JSON.stringify([
      "Preheat the oven to 350\u00B0F.",
      "<b>Melt</b> the butter.",
      "To a large bowl, add the melted butter, margarine, granulated sugar and brown sugar.",
      "When the mixture is cool enough to touch, add in the eggs, vanilla and cinnamon. Mix until well-combined.",
      "Add the flour, salt and baking sodda. Mix until well-combined.",
      "Add the Chocoalte Chips and mix until they are evenly distributed throughout the batter.",
      "Prepare a baking sheet with some parchment paper.",
      "Bake at 350\u00B0F for 10-12 mins until just golden. <br><i><b>Tip:</b> I prefer to underbake these cookies so that you can toss them into the airfryer later and give them a quick heat up before scarfing it down with a tall glass of milk.</i>",
      "Leave the cookies to cool for at least 20 mins.",
      "Store the cookies in an airtight container or ziplock bag.",
    ]),
    createdAt: new Date(2025, 11, 15),
  },
  {
    title: "Chocolate Raspberry Mousse Cake",
    slug: "chocolate-raspberry-mousse-cake",
    tags: JSON.stringify(["Desserts"]),
    image: "/images/raspberry-chocolate-mousse.png",
    rating: 4,
    views: 3,
    bookmarked: false,
    featured: false,
    cookTime: "6h",
    baseServings: 12,
    minServings: 12,
    servingIncrement: 12,
    directions: JSON.stringify([
      "title: Cake Layer:",
      "Preheat the over to 350\u00B0F.",
      "Grease a 9-inch springform pan.",
      "In a large bowl, mix the water, oil and vinegar until well combined.",
      "Add the flour, sugar, sifted cocoa powder, and baking soda. Mix until well combined.",
      "Bake at 350\u00B0F for 10 to 12 minutes until a toothpick inserted into the center comes out clean.",
      "Leave to cool completely making sure that you <b>DO NOT remove it from its pan.</b>",
      "title: Raspberry Mousse Layer:",
      "In a small bowl, sprinkle the gelatin over the 1 tbsp of water and let bloom for 5 minutes.",
      "Meanwhile, in a small saucepan, add the raspberries, lemon juice, vanilla extract, granulated sugar and water. Whisk constantly over medium-heat until the sauce coats the back of a spoon and ressembles thick jam-consistency.",
      "Remove the saucepan from the head and stir in the bloomed gelatin mixture until well combined. Set the mixture aside to cool.",
      "In another bowl, whip the cream with an electric mixer until stiff peaks form. Mix in one quarter of the whipped cream to the cooled raspberry mixture. Then <b>gently</b> fold in the remaining cream.",
      "Spoon the raspberry mixture onto the cake layer.",
      "Place the cake into the fridge for at least 4 hours, or freeze for 2 hours.",
      "title: Chocolate Mousse Layer:",
      "In a small bowl, sprinkle the gelatin over the 1 tbsp of water and let bloom for 5 minutes.",
      "Melt your chocolate using either a bowl placed on top of a pot of simmering water, or using the microwave.",
      "In a separate bowl placed on top of a pot of simmering water, or using the microwave, and in a 1/3 cup of the cream with the sugar. Heat until the sugar has dissolved. Remove from the heat and add the gelatin mixture until well combined.",
      "Add the cream mixture to the warmed chocolate and mix until well combined.",
      `In another bowl, whip the cream with an electric mixer until stiff peaks form. Mix in one quarter of the whipped cream to the cooled chocolate mixture. Then gently fold in the remaining whipped cream.`,
      "Spoon the chocolate mousse onto the raspberry layer.",
      "Place the cake into the fridge for at least 4 hours, or freeze for 2 hours.",
      "title: Chocolate Ganache Glaze:",
      "Prepare a tray with wax paper and place a wire rack over it. Take the cake out of the springform pan and place the cake on top of the wire rack. This setup should allow you to catch any ganache that is poured over. If frozen, leave the cake out for 1 hour to let it come up to room temperature.",
      "Place the chocolate into a bowl.",
      "In a small saucepan, or using the microwave, bring the cream to a boil. Add the cream to the bowl of chocolate in small increments while stirring until the mixture is smooth. Then pour in the remaining cream. With a spatula, stir the ganache until smooth.",
      "Pour the chocolate ganache over the cake so that the entire cake is glazed.",
    ]),
    createdAt: new Date(2020, 12, 20),
  },
  {
    title: "Fluffy Blueberry Muffins",
    slug: "fluffy-blueberry-muffins",
    tags: JSON.stringify(["Breakfast", "Desserts", "Easecipes"]),
    image: "/images/fluffy-blueberry-muffins.png",
    rating: 4,
    views: 11,
    bookmarked: false,
    featured: false,
    cookTime: "45 min",
    baseServings: 12,
    minServings: 12,
    servingIncrement: 12,
    directions: JSON.stringify([
      "Set to 375\u00B0F.",
      "In a mixer, cream the butter and sugar until light.",
      "Add the eggs, vanilla and milk. Mix until well-combined.",
      "Add the flour, salt and baking powder. Mix until well-combined.",
      "Fold-in the blueberries.",
      "Grease a standard muffin tin and fill with batter.",
      `Bake at 375\u00B0F for 30-35 mins.`,
      "Remove muffins from tin and leave them to cool for at least 30 mins.",
      "Store the muffins uncovered or else the muffins will be too moist on the second day.",
    ]),
    createdAt: new Date(2025, 6, 10),
  },
  {
    title: "Grammy Vint's Good Bean Salad",
    slug: "grammy-vints-good-bean-salad",
    tags: JSON.stringify(["Sides", "Easecipes", "Potluck"]),
    image: "/images/bean-salad.png",
    rating: 5,
    views: 6,
    bookmarked: false,
    featured: false,
    cookTime: "15 min",
    baseServings: 24,
    minServings: 24,
    servingIncrement: 24,
    directions: JSON.stringify([
      "In a large bowl, combine chickpeas, kidney beans, black beans, corn ,onion, and red pepper.",
      "In a small bowl, whisk together vinegar, basil, olive oil, Dijon mustard, garlic, salt, hot pepper sauce and pepper.",
      "Pour contents of small bowl over contents of big bowl and toss together.",
      "Taste and adjust seasoning as necessary.",
      "Garnish with chopped parsley.",
      "Serve at room temperature. You can throw this together up to one day ahead of time.",
    ]),
    createdAt: new Date(2019, 3, 15),
  },
  {
    title: "Grammy Vint's Rhubarb Cream Crisp",
    slug: "grammy-vints-rhubarb-cream-crisp",
    tags: JSON.stringify(["Desserts"]),
    image: "/images/rhubarb-cream-crisp.jpg",
    rating: 4,
    views: 7,
    bookmarked: false,
    featured: false,
    cookTime: "1h",
    baseServings: 12,
    minServings: 12,
    servingIncrement: 12,
    directions: JSON.stringify([
      "Preheat oven to 400\u00B0F. Grease a 9\" deep baking dish and set it aside.",
      "Melt the butter.",
      "In a large bowl, mix the ingredients for the filling together until well-combined. Pour the mixture into the baking dish.",
      "Cut the cold butter up into cubes using a knife and add it to the same large bowl.",
      "In the same large bowl, mix the ingredients for the crumble topping together until all ingredients are well-distributed.",
      "Scatter the crumble mixture all over the top of the filling, and place the baking dish into the over for 40 to 45 minutes or until beautifully golden brown.",
    ]),
    createdAt: new Date(2019, 5, 20),
  },
  {
    title: "Merry Minced Meat Pies",
    slug: "merry-minced-meat-pies",
    tags: JSON.stringify(["Desserts", "Potluck"]),
    image: "/images/mince-meat-pies.jpg",
    rating: 4,
    views: 7,
    bookmarked: false,
    featured: false,
    cookTime: "6h",
    baseServings: 12,
    minServings: 12,
    servingIncrement: 12,
    directions: JSON.stringify([
      "title: Minced Meat Filling:",
      "Melt the butter.",
      "Toss all of the filling ingredients, juice of the lemon and melted butter into a large oven-safe casserol. Set the mixture aside of a minimum of 3 hours or overnight to allow the dried fruit to rehydrate.",
      "Preheat oven to 230\u00B0F.",
      "Cover the casserol dish with foil and bake for 2-1/2 hours.",
      "Once cooled, stir in the brandy/rum/whiskey.",
      "title: Dough:",
      "Combine all dry ingredients and the egg in a large bowl.",
      "To the large bowl, add cubed cold butter. Mix in the butter using a pastry blender or a fork.",
      "Add just enough cold water to get the dough to form together without falling apart with a little pressure.",
      "Form the dough into a square using clingwrap and a rolling pin. Set the dough in the fridge to cool for at least 1 hour.",
      "title: Assemble:",
      "Preheat oven to 400\u00B0F.",
      "Grease a muffin tin.",
      "Roll out the dough and use a circular cutout that is big enough to fit in the base of the muffin tin and come halfway up the sides of the muffin mould to create disks for the base of the tart. Use any other shaped cutout for the tart topper.",
      "Place the circular cutout at the bottom of the muffin tin, fill to the top with the minced meat filling, and top with the tart topper cutout.",
      "Bake the pies for 15 mins."
    ]),
    createdAt: new Date(2025, 12, 20),
  },
  {
    title: "Onion Pancakes",
    slug: "onion-pancakes",
    tags: JSON.stringify(["Breakfast"]),
    image: "/images/onion-pancakes.png",
    rating: 4,
    views: 13,
    bookmarked: false,
    featured: false,
    cookTime: "2h",
    baseServings: 6,
    minServings: 6,
    servingIncrement: 6,
    directions: JSON.stringify([
      "Combine flour and salt together in a large bowl or mixer.",
      "Slowly add boiling water to the bowl while mixing using a fork until it forms a shaggy dough. It is normal at this point for the dough to not come together yet.",
      "Add your chopped-up green onion tips and your egg(s) to the mixture and continue to mix with your fork until the egg is well-combined.",
      "Knead your dough either by hand, or using a mixer with a dough-hook attachment until it forms a smooth dough.",
      "Roll the dough out into a sausage form and divide it into 6 equal pieces. Form each piece into a ball and brush with a bit of oil. Cover the dough balls and set aside to rest for 40 mins in a warm place.",
      "Flatten each ball into a round, trying to get it as thin as possible. Brush the spread onto the round, avoiding the edges. Make a slit in the round from its center to its border. Wrap the round in on itself into a cone as illustrated in the video to create the layers in the pastry. Roll the cone out back into a round. <br><i><b>Tip:</b> You can freeze your uncooked pancakes for up to a month at this point. Just place some parchment paper or some wax paper in between your pancakes and store in a ziplock bag.</i>",
      "When you are ready to eat, fry-up the pancakes (no need to defrost if cooking from frozen) in a skillet with a little oil. Serve whilst hot."
    ]),
    createdAt: new Date(2022, 1, 20),
  },
  {
    title: "Thai Chicken Peanut Noodles",
    slug: "thai-chicken-peanut-noodles",
    tags: JSON.stringify(["Mains", "Thai", "Fusion"]),
    image: "/images/thai-chicken-peanut-noodles.jpg",
    rating: 4,
    views: 15,
    bookmarked: false,
    featured: false,
    cookTime: "45 min",
    baseServings: 4, 
    minServings: 4,
    servingIncrement: 4,
    directions: JSON.stringify([
      "title: Marinade:",
      "In a bowl, mix together the salt, oil, minced garlic, ginger powder, lime juice and chopped coriander",
      "Add the chicken to the marinade and let it sit for at least 30 mins.",
      "title: Peanut Sauce:",
      "In a small saucepan, add water, sugar, peanut butter, soy sauce, and garlic.",
      "Take the saucepan off the heat and stir in sriracha to taste.",
      "title: Noodles:",
      "Cook the noodles according to package instructions. Drain and set aside.",
      "title: Stir Fry:",
      "Slice up the onions and the carrots into long strips, and chop up the zucchini into half-moons.",
      "In a large pan (preferrably a wok), heat some oil and cook the chicken through (around 4 minutes on each side).",
      "Chop up the chicken into bite-sized pieces and set aside.",
      "Whisk eggs and salt together in a bowl.",
      "In the same pan, add a little more oil and pour in the egg mixture. Scramble the eggs until they are fully cooked. Set the scrambled eggs aside with the chicken.",
      "In the same pan, add the onions and carrots and stir fry for 3 mins.", 
      "Add in the zucchini and stir fry until they are cooked but still crisp. (About 2 mins).",
      "title: Assemble:",
      "In the same pan, add the chicken, eggs, noodles and peanut sauce.",
      "Toss everything together until well-combined and heated through.",
      "Serve with chopped cilantro on top.",
    ]),
    createdAt: new Date(2026, 2, 10),
  },
];

const seedIngredientMeasUnit = [
  // Apple Frangipane Tart
  {recipe_id: 'apple-frangipane-tart', component: 'Dough:', amount: '1', measUnit_id: ' ', ingredient_id: 'Premade 9 inch Pie Crust', min_amount: '1'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '4', measUnit_id: 'tbsp(s)', ingredient_id: 'Unsalted Butter', min_amount: '4'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Granulated Sugar', min_amount: '1/4'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Almond Flour', min_amount: '1/2'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '1/4', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/4'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '1', measUnit_id: 'tbsp(s)', ingredient_id: 'Flour', min_amount: '1'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '1', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '1'},
  {recipe_id: 'apple-frangipane-tart', component: 'Filling:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Vanilla Extract', min_amount: '1'},
  {recipe_id: 'apple-frangipane-tart', component: 'Toppings:', amount: '2', measUnit_id: ' ', ingredient_id: 'Apple(s)', min_amount: '2'},
  //Black Sesame Paste
  {recipe_id: 'black-sesame-paste', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Black Sesame Seeds', min_amount: '1/2'},
  {recipe_id: 'black-sesame-paste', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Water', min_amount: '2'},
  {recipe_id: 'black-sesame-paste', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Honey / Maple Syrup', min_amount: '1/4'},
  //Black Sesame Swirl Buns
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '3/4', measUnit_id: 'cup(s)', ingredient_id: 'Whole Milk', min_amount: '3/4'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '2 1/4', measUnit_id: 'tsp(s)', ingredient_id: 'Yeast', min_amount: '2 1/4'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Granulated Sugar', min_amount: '1/4'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '1', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '1'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '1', measUnit_id: ' ', ingredient_id: 'Egg Yolk(s)', min_amount: '1'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Unsalted Butter', min_amount: '1/4'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '2 3/4', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '2 3/4'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Dough:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Black Sesame Paste:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Black Sesame Seeds', min_amount: '1/2'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Black Sesame Paste:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Honey / Maple Syrup', min_amount: '1/4'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Filling:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Unsalted Butter', min_amount: '2'},
  {recipe_id: 'black-sesame-swirl-buns', component: 'Filling:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Black Sesame Paste', min_amount: '1/2'},
  //Chocolate Chip Cookies
  {recipe_id: 'chocolate-chip-cookies', amount: '3/4', measUnit_id: 'cup(s)', ingredient_id: 'Unsalted Butter', min_amount: '3/8'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Margarine', min_amount: '1/8'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Granulated Sugar', min_amount: '1/4'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1', measUnit_id: 'cup(s)', ingredient_id: 'Brown Sugar', min_amount: '1/2'},
  {recipe_id: 'chocolate-chip-cookies', amount: '2', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '1'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Vanilla Extract', min_amount: '1/2'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1/8', measUnit_id: 'tsp(s)', ingredient_id: 'Ground Cinnamon', min_amount: '1/16'},
  {recipe_id: 'chocolate-chip-cookies', amount: '2 1/4', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '1 1/8'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'chocolate-chip-cookies', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Baking Soda', min_amount: '1/2'},
  {recipe_id: 'chocolate-chip-cookies', amount: '2', measUnit_id: 'cup(s)', ingredient_id: 'Semisweet Chocolate Chips', min_amount: '1'},
  //Chocolate Raspberry Mousse Cake
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Water', min_amount: '1/4'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '4', measUnit_id: 'tsp(s)', ingredient_id: 'Canola Oil', min_amount: '4'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '2', measUnit_id: 'tsp(s)', ingredient_id: 'White Vinegar', min_amount: '2'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '1/3', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '1/3'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '3', measUnit_id: 'tbsp(s)', ingredient_id: 'Granulated Sugar', min_amount: '3'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '1 1/2', measUnit_id: 'tbsp(s)', ingredient_id: 'Cocoa Powder', min_amount: '1 1/2'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Cake Layer:', amount: '1/8', measUnit_id: 'tsp(s)', ingredient_id: 'Baking Soda', min_amount: '1/8'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Gelatin Powder', min_amount: '1'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1', measUnit_id: 'tbsp(s)', ingredient_id: 'Water', min_amount: '1'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '2', measUnit_id: 'cup(s)', ingredient_id: 'Raspberries', min_amount: '2'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Lemon Juice', min_amount: '1'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Vanilla Extract', min_amount: '1'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1', measUnit_id: 'tbsp(s)', ingredient_id: 'Granulated Sugar', min_amount: '1'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1/8', measUnit_id: 'cup(s)', ingredient_id: 'Water', min_amount: '1/8'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Raspberry Mousse:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Heavy Cream', min_amount: '1/4'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Mousse:', amount: '140', measUnit_id: 'g', ingredient_id: 'Dark Chocolate, chopped', min_amount: '140'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Mousse:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Gelatin Powder', min_amount: '1'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Mousse:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Water', min_amount: '2'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Mousse:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Granulated Sugar', min_amount: '1/2'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Mousse:', amount: '1 1/3', measUnit_id: 'cup(s)', ingredient_id: 'Heavy Cream', min_amount: '1 1/3'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Ganache Glaze:', amount: '85', measUnit_id: 'g', ingredient_id: 'Dark Chocolate, chopped', min_amount: '85'},
  {recipe_id: 'chocolate-raspberry-mousse-cake', component: 'Chocolate Ganache Glaze:', amount: '1/3', measUnit_id: 'cup(s)', ingredient_id: 'Heavy Cream', min_amount: '1/3'},
  // Fluffy Blueberry Muffins
  {recipe_id: 'fluffy-blueberry-muffins', amount: '1/3', measUnit_id: 'cup(s)', ingredient_id: 'Unsalted Butter', min_amount: '1/3'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Vegetable Oil', min_amount: '2'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '1', measUnit_id: 'cup(s)', ingredient_id: 'Brown Sugar', min_amount: '1'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '2', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '2'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Vanilla Extract', min_amount: '1'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Milk', min_amount: '1/2'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '2', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '2'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '2', measUnit_id: 'tsp(s)', ingredient_id: 'Baking Powder', min_amount: '2'},
  {recipe_id: 'fluffy-blueberry-muffins', amount: '2', measUnit_id: 'cup(s)', ingredient_id: 'Blueberries', min_amount: '2'},
  //Grammy Vint's Good Bean Salad
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: '19 oz can', ingredient_id: 'Chickpeas', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: '19 oz can', ingredient_id: 'Kidney Beans', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: '15 oz can', ingredient_id: 'Black Beans', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: '12 oz can', ingredient_id: 'Corn Kernels', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Red Onion, diced', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: ' ', ingredient_id: 'Sweet Red Pepper, diced', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Red Wine Vinegar / Apple Cider Vinegar', min_amount: '1/2'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Basil', min_amount: '2'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1/3', measUnit_id: 'cup(s)', ingredient_id: 'Olive Oil', min_amount: '1/3'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: 'tbsp(s)', ingredient_id: 'Dijon Mustard', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: 'clove(s) of', ingredient_id: 'Garlic, minced', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Hot Sauce', min_amount: '1/2'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Black Pepper', min_amount: '1/2'},
  {recipe_id: 'grammy-vints-good-bean-salad', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Fresh Parsley', min_amount: '1/2'},
  //Grammy Vint's Rhubarb Cream Crisp
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Filling:', amount: '3', measUnit_id: 'cup(s)', ingredient_id: 'Rhubarb, chopped', min_amount: '3'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Filling:', amount: '2', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '2'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Filling:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Unsalted Butter', min_amount: '2'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Filling:', amount: '1', measUnit_id: 'cup(s)', ingredient_id: 'Granulated Sugar', min_amount: '1'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Filling:', amount: '3', measUnit_id: 'tbsp(s)', ingredient_id: 'Flour', min_amount: '3'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Crumble Topping:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '1/2'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Crumble Topping:', amount: '3/4', measUnit_id: 'cup(s)', ingredient_id: 'Quick Oats', min_amount: '3/4'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Crumble Topping:', amount: '3/4', measUnit_id: 'cup(s)', ingredient_id: 'Brown Sugar', min_amount: '3/4'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Crumble Topping:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Baking Powder', min_amount: '1'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Crumble Topping:', amount: '1/3', measUnit_id: 'cup(s)', ingredient_id: 'Unsalted Butter', min_amount: '1/3'},
  {recipe_id: 'grammy-vints-rhubarb-cream-crisp', component: 'Crumble Topping:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Walnuts (optional)', min_amount: '1/4'},
  //Merry Minced Meat Pies
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '100', measUnit_id: 'g', ingredient_id: 'Orange Marmelade', min_amount: '100'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '100', measUnit_id: 'g', ingredient_id: 'Raisins', min_amount: '100'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '200', measUnit_id: 'g', ingredient_id: 'Golden Raisins', min_amount: '200'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '100', measUnit_id: 'g', ingredient_id: 'Cranberries', min_amount: '100'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '50', measUnit_id: 'ml', ingredient_id: 'Orange Juice', min_amount: '50'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '110', measUnit_id: 'g', ingredient_id: 'Brown Sugar', min_amount: '110'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '1', measUnit_id: ' ', ingredient_id: 'Apple(s)', min_amount: '1'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '1/2', measUnit_id: ' ', ingredient_id: 'Lemon(s)', min_amount: '1/2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '1 1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Ground Cinnamon', min_amount: '1 1/2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Ginger Powder', min_amount: '1/2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Ground Cloves', min_amount: '1/2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Black Pepper', min_amount: '1/2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '125', measUnit_id: 'g', ingredient_id: 'Unsalted Butter', min_amount: '125'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Filling:', amount: '3', measUnit_id: 'tbsp(s)', ingredient_id: 'Brandy / Rum / Whiskey', min_amount: '3'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '250', measUnit_id: 'g', ingredient_id: 'Flour', min_amount: '250'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Almond Flour', min_amount: '2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '50', measUnit_id: 'g', ingredient_id: 'Granulated Sugar', min_amount: '50'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '150', measUnit_id: 'g', ingredient_id: 'Unsalted Butter', min_amount: '150'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '1', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '125'},
  {recipe_id: 'merry-minced-meat-pies', component: 'Dough:', amount: '4', measUnit_id: 'tbsp(s)', ingredient_id: 'Ice Cold Water', min_amount: '4'},
  // Onion Pancakes
  {recipe_id: 'onion-pancakes', component: 'Dough:', amount: '1 3/4', measUnit_id: 'cup(s)', ingredient_id: 'Flour', min_amount: '1 3/4'},
  {recipe_id: 'onion-pancakes', component: 'Dough:', amount: '3', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '3'},
  {recipe_id: 'onion-pancakes', component: 'Dough:', amount: '1', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '1'},
  {recipe_id: 'onion-pancakes', component: 'Dough:', amount: '1/2', measUnit_id: 'cup(s)', ingredient_id: 'Hot Water', min_amount: '1/2'},
  {recipe_id: 'onion-pancakes', component: 'Dough:', amount: '3', measUnit_id: ' ', ingredient_id: "Tips of Green Onions", min_amount: '3'},
  {recipe_id: 'onion-pancakes', component: 'Spread:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Salted Butter', min_amount: '1/4'},
  {recipe_id: 'onion-pancakes', component: 'Spread:', amount: '3', measUnit_id: ' ', ingredient_id: 'Whites of Green Onions', min_amount: '3'},
  //Thai Chicken Peanut Noodles
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Vegetable Oil', min_amount: '2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '4', measUnit_id: 'clove(s) of', ingredient_id: 'Garlic, minced', min_amount: '4'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '1', measUnit_id: 'tsp(s)', ingredient_id: 'Ginger Powder', min_amount: '1'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '1', measUnit_id: ' ', ingredient_id: 'Lime', min_amount: '1'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Coriander', min_amount: '1/4'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Marinade:', amount: '4', measUnit_id: ' ', ingredient_id: 'Chicken Thighs, boneless', min_amount: '4'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Peanut Sauce:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Water', min_amount: '1/4'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Peanut Sauce:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Granulated Sugar', min_amount: '2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Peanut Sauce:', amount: '1/4', measUnit_id: 'cup(s)', ingredient_id: 'Peanut Butter', min_amount: '1/4'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Peanut Sauce:', amount: '2', measUnit_id: 'tbsp(s)', ingredient_id: 'Soy Sauce', min_amount: '2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Peanut Sauce:', amount: '1', measUnit_id: 'clove(s) of', ingredient_id: 'Garlic, minced', min_amount: '1'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Peanut Sauce:', amount: '2', measUnit_id: 'tsp(s)', ingredient_id: 'Sriracha', min_amount: '2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Noodles:', amount: '12', measUnit_id: 'oz(s)', ingredient_id: 'Vermicelli Noodles', min_amount: '12'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Stir Fry:', amount: '2', measUnit_id: ' ', ingredient_id: 'Egg(s)', min_amount: '2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Stir Fry:', amount: '1/2', measUnit_id: 'tsp(s)', ingredient_id: 'Salt', min_amount: '1/2'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Stir Fry:', amount: '1', measUnit_id: 'tbsp(s)', ingredient_id: 'Vegetable Oil', min_amount: '1'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Stir Fry:', amount: '1', measUnit_id: ' ', ingredient_id: 'Onion(s)', min_amount: '1'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Stir Fry:', amount: '1', measUnit_id: ' ', ingredient_id: 'Carrot(s)', min_amount: '1'},
  {recipe_id: 'thai-chicken-peanut-noodles', component: 'Stir Fry:', amount: '1', measUnit_id: ' ', ingredient_id: 'Zucchini', min_amount: '1'},
];

async function seed() {
  console.log('Seeding database...');

  // Clear existing data
  db.delete(recipe_ingredient_measUnit).run(); // this line must run first (child tables must be deleted before parent tables due to foreign key constraints)
  db.delete(recipes).run();
  db.delete(ingredients).run();
  db.delete(measurementUnits).run();

  // Insert seed data
  for (const ingredient of seedIngredients) {
    db.insert(ingredients).values(ingredient).run();
  }
  console.log(`Seeded ${seedIngredients.length} ingredients`);

  for (const measUnit of seedMeasurementUnits) {
    db.insert(measurementUnits).values(measUnit).run();
  }
  console.log(`Seeded ${seedMeasurementUnits.length} measurement units...`)

  for (const recipe of seedRecipes) {
    db.insert(recipes).values(recipe).run();
  }
  console.log(`Seeded ${seedRecipes.length} recipes`);

  for (const rim of seedIngredientMeasUnit) {
    db.insert(recipe_ingredient_measUnit).values(rim).run();
  }
  console.log(`Seeded ${seedIngredientMeasUnit.length} recipe-ingredient-measurementUnit relationships...`)

  // Verify the data
  const allRecipes = db.select().from(recipes).all();
  console.log('All recipes:', allRecipes);
}

seed().catch(console.error);
